version: '3.8'

services:
  # Next.js Health Helper App
  health-helper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AI_API_URL=http://ai-api:8000
      - NODE_ENV=production
    depends_on:
      - ai-api
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - health-network

  # Python AI API Server
  ai-api:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///app/data/unified_health.db
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - health-network
    command: python -m uvicorn src.lib.api_server:app --host 0.0.0.0 --port 8000

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - health-network

  # PostgreSQL (for production)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=health_ai
      - POSTGRES_USER=health_user
      - POSTGRES_PASSWORD=health_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - health-network

volumes:
  postgres_data:

networks:
  health-network:
    driver: bridge
